### ISSUE TITLE
Can't create Action without ActionCloseOnTrigger flag

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#26]
Parent fact will be closed, when FactAction is clicked, no matter ActionCloseOnTrigger set or not.
No difference between
`m_applyButton(new FactAction(this, "apply", "Apply", "", "", FactAction::ActionApply)),`
and
`m_applyButton(new FactAction(this, "apply", "Apply", "", "", FactAction::ActionApply | FactAction::ActionCloseOnTrigger)),`

**Comment by uavinda** [comment]
just tested again - action never closes the fact, although it may close when fact deleted
