### ISSUE TITLE
AppImage self auto update for Linux

### ISSUE THREAD

**Issue by uavinda** [uavos/apx-releases#28]
download from github releases, support for incremental updates.

**Comment by uavinda** [comment]
bump

**Comment by smarttowel** [comment]
Do you have idea, how to implement it?

I see several problems:
1. No standard dir for .AppImage applications in Linux (like Applications in MacOS). So, in which dir we should place updated GCS?
2. What about filename? We have different .AppImage names for different GCS versions. We should keep old and new? Or remove old? What about symbolic links to GCS(f.ex. from Desktop)?
