### ISSUE TITLE
Brakes and gimbal problem

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#29]
Gimbal can't moving, while ctr_brake=1. I think, bldc in gimbal should be ignore brakes command.

**Comment by smarttowel** [comment]
Пишу за сутки.
Могу завтра организовать.

**Comment by uavinda** [comment]
Ok. I'm available from 9am to 9pm Miami time.

**Comment by uavinda** [comment]
The issue is related to custom BLDC firmware `gd3f28`. Can't find one in the APX or autopilot tree.

**Comment by uavinda** [comment]
---------- Forwarded message ---------
From: Yury Kapacheuski <ky@uavos.com>
Date: Thu, Jun 20, 2019, 10:49
Subject: Обновление прошики BLDC
To: Pawel Mikhadzionak <pmv@uavos.com>, Aliaksei Stratsilatau <sa@uavos.com>,
Ruslan Lysenka <lr@uavos.com>, Egor Volkov <ve@uavos.com>


В данной версии система не выключает двигатели по команде “brakes” если в
конфигурации  не установлена настройка выхода на тормоз.
(FOC:Diskrets:dBrake)
