### ISSUE TITLE
Too slow downloading nodes configuration via modem

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#34]
APX
modem: can't download nodes, multiple "Service timeout" in console
ghanta: works fine

GCU 9.x
modem: works fine
ghanta: works fine

**Comment by smarttowel** [comment]
Firmware version 9.x

**Comment by uavinda** [comment]
How is modem connected to PC?

**Comment by smarttowel** [comment]
USB-COM converter "МастерКит"

**Comment by uavinda** [comment]
Couldn't you attach telemetry file?

**Comment by smarttowel** [comment]
I can, but tomorrow.
What kind of telemetry you need? Just ~1 minute, when I try to download configuration?

**Comment by uavinda** [comment]
Correct.

**Comment by smarttowel** [comment]
[2019_06_20_11_11_54_984-Heli_E_#2.telemetry.zip](https://github.com/uavos/apx-releases/files/3309433/2019_06_20_11_11_54_984-Heli_E_.2.telemetry.zip)

**Comment by smarttowel** [comment]
My custom plugin set vars VM1 and VM2 every 10 msecs via setValue(...) method. 
By design VM* variables shouldn't send over network, but in real it's does.
I solved this problem by using setValueLocal(...) method.

**Comment by uavinda** [comment]
By design VM* variables shouldn't send over network, but in real it's does.

Should this behavior be fixed? If so - create issue.

Regards,
Aliaksei Stratsilatau
http://www.uavos.com/
