### ISSUE TITLE
Crash when try to open "Video" tool

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#35]
Sometimes segfault happens when I click on Tools->Video plugin

**Comment by uavinda** [comment]
Which OS?

**Comment by smarttowel** [comment]
Linux

**Comment by uavinda** [comment]
It doesn't have proper gst libs in the package. The QBS packaging of
AppImage must be fixed. There're lots of errors in the console on streaming
plugin load.

**Comment by smarttowel** [comment]
Please, review the PR. It's fixed problem with this segfault.
I can't see video on Linux, but it's another problem.
