### ISSUE TITLE
QML instrument to operate payloads or user defined controls similar to `numbers` and `old joystick`

### ISSUE THREAD

**Issue by uavosvn** [uavos/apx-releases#36]
*Hi,
Do we need an define file for joystick and button like /.gcu/config/default.js ? Cause It's easy  config button like in old GCU (ex make an button for Zoom in and Zoom out etc...).
Regards,
H.Minh

**Comment by uavinda** [comment]
Please, attach log files from Documents/UAVOS/Logs

**Comment by uavinda** [comment]
now controlled through video plugin
