### ISSUE TITLE
Numbers display error Ground Control 10.1.53

### ISSUE THREAD

**Issue by carbonlof** [uavos/apx-releases#43]
**Describe the bug**
The "numbers" feature is configured to display 7 variables, however only first 4 of them are shown.

**Comment by uavinda** [comment]
Pls, attach configuration from UAVOS/Preferences/numbers.json

**Comment by carbonlof** [comment]
[numbers.json.txt](https://github.com/uavos/apx-releases/files/3380862/numbers.json.txt)

**Comment by uavinda** [comment]
the latest version seem to resolve this issue.
