### ISSUE TITLE
Telemetry plugin sometimes can't show one variable

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#51]
I want to see one variable from my telemetry, so I do:

1. Click on green button (load latest telemetry)
2. Click on CLR button
3. Choose one variable (f.ex. user2) and no graphics displayed
4. Choose one more variable (f.ex., user3), or scale graphics and I see missed var.
![bug1](https://user-images.githubusercontent.com/1128528/62876592-f4d09880-bd2d-11e9-9586-11951038408e.png)
![bug2](https://user-images.githubusercontent.com/1128528/62876593-f4d09880-bd2d-11e9-8b48-f34987e9ff46.png)

**Comment by uavinda** [comment]
This might be QWT issue. What happens when you just adjust zoom a little bit before your step 4?

**Comment by smarttowel** [comment]
Yes, I can see missed var in this case.

**Comment by smarttowel** [comment]
If it is QWT bug, what about Qt Charts usage?

**Comment by uavinda** [comment]
I actually wanna move to QtCharts, but have lots of higher priority tasks..
