### ISSUE TITLE
Videoplugin is broken in v10.1.154 release

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-releases#52]
Problem occured only on Linux. Kubuntu 18.04.

But if I build project from sources (release and debug builds), plugin works fine.
I think, it's can be travis related problem. Maybe, we should make linux build under bionic, not xenial distro?

[log.txt](https://github.com/uavos/apx-releases/files/3496340/log.txt)

**Comment by smarttowel** [comment]
Ok, now we don't have errors in console, but video still not working in build from travis.
With `GST_DEBUG="*:3"`:

Missing parser: H.264 (Main Profile) (video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3, profile=(string)main, codec_data=(buffer)014d401effe000, width=(int)1920, height=(int)1072, framerate=(fraction)113/4, pixel-aspect-ratio=(fraction)1/1, parsed=(boolean)true)

Looks like h264parse element not found.

**Comment by smarttowel** [comment]
Bump

**Comment by uavinda** [comment]
Travis build log: https://api.travis-ci.com/v3/job/230905203/log.txt?log.token=2s8B8-hGqXuzrFRuNm0Omw

**Comment by uavinda** [comment]
It looks like some libs are missing:
![Screen Shot 2019-09-08 at 16 53 05](https://user-images.githubusercontent.com/160358/64489225-48fd6880-d259-11e9-84aa-ef611f550d8f.png)

**Comment by smarttowel** [comment]
Are you sure that it's screenshot from Release .AppImage build?
I check v10.1.190 right now and all libraries presented in .AppImage.

**Comment by uavinda** [comment]
Sure I am. After copying of the missing libs, the image works fine.
