### ISSUE TITLE
Numbers window

### ISSUE THREAD

**Issue by Raitvok** [uavos/apx-releases#58]
If title longer than 5 symbols, it is value overlaps number of value. 

<img width="106" alt="Снимок экрана 2019-08-27 в 11 18 08" src="https://user-images.githubusercontent.com/36848314/63753943-af2ed680-c8bc-11e9-96d8-b6ee2f7636d3.png">

I think you can create a table with two columns. Set a fixed width in them. Position the left column on the left side, the right column on the right side. Or limit the number of characters of a name or value.

APX 10.1.165
macOS Mojave 10.14.3

**Comment by smarttowel** [comment]
I think, correct Text.width with Text.elide can be a good solution.
