### ISSUE TITLE
APX does not work with bb_reader

### ISSUE THREAD

**Issue by Raitvok** [uavos/apx-releases#68]
When starting APX with bb_reader, the program does not start.
[log at Crash APX](https://github.com/uavos/apx-releases/files/3678042/Crash.APX.txt)

[APX 10.1.229](https://github.com/uavos/apx-releases/releases/tag/10.1.229)
[bb_reader 0.1.2](https://github.com/uavos/apx_bbreader/releases/tag/0.1.2)

OS: ubuntu 18.04
Notebook: Dell

**Comment by smarttowel** [comment]
New apx_bbreader 0.1.3 version available.
