### ISSUE TITLE
Gimbal control stuck in video plugin.

### ISSUE THREAD

**Issue by uavosvn** [uavos/apx-releases#83]
Hi,
When I change gimbal control to speed mode and  move mouse for turn, she turn around non stop until we change direction and continue turn when you move mouse out of area. After that, I change to stab mode, she turn slowly and lost stop position until I press cam_off. Also, a mark of control cover our vision.
Regards,
H.Minh

**Comment by uavinda** [comment]
it looks like gimbal configuration problem. Can we make a VPN connection to debug this?
