### ISSUE TITLE
позиционирование gimbal in mode STAB Look here

### ISSUE THREAD

**Issue by zeuavos** [uavos/apx-releases#98]
При установлении режима look here gimbal следит за yaw and pitch. Если просто mode_stab, то  вносится автопилотом ошибочная коррекция (командные значение). В этот же момент ставишь mode speed, то gimbal отлично стабилизируется.
При этом всем маркер куда смотрит gimbal постоянно отражает некорректное положение

**Comment by uavinda** [comment]
config problem: `shiva/Regulator/Gimbal/stab` must be `on`
